#!/bin/bash

#$ sudo crontab -l | grep sync
# 30 6 * * * /home/ropeck/sync-backup

/usr/bin/mount -o rw -t drvfs '\\nas\nas' /mnt/nas || exit 1
#rsync -aX $(find  /mnt/e/Macrium/ -mtime -1  -type f) /mnt/nas $*
/usr/bin/rsync -a --delete /mnt/e/Macrium/backup/ /mnt/nas/backup $*

