#!/bin/bash

#$ sudo crontab -l | grep sync
# 30 6 * * * /home/ropeck/sync-backup
start=$(date +%s)
RUNNING=$(ps -eflww | grep -c usr/bin/rsync)
if [ $RUNNING -ne 1 ]; then
	echo "rsync active"
	ps -eflww|grep rsync
	exit 1
fi

# Function takes a single argument, the number of seconds
show_time() {
    # Catch arguments
    SECONDS="$1"

    # Calculate hours, minutes, and seconds
    HH=$(($SECONDS / 3600))
    SECONDS=$(($SECONDS % 3600))
    MM=$(($SECONDS / 60))
    SS=$(($SECONDS % 60))

    # Output time
    if [ $HH -gt 0 ]; then
        printf "%d:%02d:%02d\n" $HH $MM $SS
    elif [ $MM -gt 0 ]; then
        printf "%d:%02d\n" $MM $SS
    else 
        printf "%d sec\n" $SS
    fi
}

/usr/bin/mount -o rw -t drvfs '\\nas\nas' /mnt/nas || exit 1
#rsync -aX $(find  /mnt/e/Macrium/ -mtime -1  -type f) /mnt/nas $*
/usr/bin/rsync -a --delete /mnt/e/Macrium/backup/ /mnt/nas/backup $*
echo -n "elapsed time: "
show_time $(($(date +%s) - $start))


